/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package L10_GUI.S10_JComboBox;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author NGHIA NGUYEN
 */
public class JComboBoxDemo2 extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public JComboBoxDemo2() {
        initComponents();
        initLocation();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderSelection = new javax.swing.ButtonGroup();
        signUpBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        resultLbl = new javax.swing.JLabel();
        usernameLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        usernameInpTxt = new javax.swing.JTextField();
        passwordInpTxt = new javax.swing.JPasswordField();
        policyCheckBtn = new javax.swing.JCheckBox();
        genderLbl = new javax.swing.JLabel();
        genderRadBtnMale = new javax.swing.JRadioButton();
        genderRadBtnFemale = new javax.swing.JRadioButton();
        genderRadBtnFlex = new javax.swing.JRadioButton();
        locationLbl = new javax.swing.JLabel();
        locationCBox = new javax.swing.JComboBox<>();
        zipCodeLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration Form");

        signUpBtn.setText("Sign Up");
        signUpBtn.setEnabled(false);
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        resultLbl.setForeground(new java.awt.Color(0, 0, 255));
        resultLbl.setToolTipText("");

        usernameLbl.setText("Username:");

        passwordLbl.setText("Password:");

        passwordInpTxt.setToolTipText("");

        policyCheckBtn.setText("I have read and accept Terms of Service");
        policyCheckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policyCheckBtnActionPerformed(evt);
            }
        });

        genderLbl.setText("Gender:");

        genderSelection.add(genderRadBtnMale);
        genderRadBtnMale.setText("Male");

        genderSelection.add(genderRadBtnFemale);
        genderRadBtnFemale.setText("Female");

        genderSelection.add(genderRadBtnFlex);
        genderRadBtnFlex.setText("Flexible");

        locationLbl.setText("Location:");

        locationCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationCBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordLbl)
                            .addComponent(usernameLbl)
                            .addComponent(genderLbl)
                            .addComponent(locationLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(signUpBtn)
                                .addGap(18, 18, 18)
                                .addComponent(clearBtn))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(usernameInpTxt)
                                .addComponent(passwordInpTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(genderRadBtnMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genderRadBtnFemale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genderRadBtnFlex))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(locationCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(zipCodeLbl))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(policyCheckBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLbl)
                    .addComponent(usernameInpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLbl)
                    .addComponent(passwordInpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLbl)
                    .addComponent(genderRadBtnMale)
                    .addComponent(genderRadBtnFemale)
                    .addComponent(genderRadBtnFlex))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLbl)
                    .addComponent(locationCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipCodeLbl))
                .addGap(18, 18, 18)
                .addComponent(policyCheckBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpBtn)
                    .addComponent(clearBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initLocation() {
        locationCBox.addItem(new Location("001", "North"));
        locationCBox.addItem(new Location("002", "Middle"));
        locationCBox.addItem(new Location("003", "South"));
    }

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        String username = usernameInpTxt.getText();
        String password = String.valueOf(passwordInpTxt.getPassword());
        String gender = null;

        if (genderRadBtnMale.isSelected()) {
            gender = "Male";
        } else if (genderRadBtnFemale.isSelected()) {
            gender = "Female";
        } else {
            gender = "Flexible";
        }

        String location = String.valueOf(locationCBox.getSelectedItem());

        JOptionPane.showConfirmDialog(rootPane,
                "Your username: " + username
                + "\nYour password: " + password
                + "\nYour gender: " + gender
                + "\nYour location: " + location);
    }//GEN-LAST:event_signUpBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        usernameInpTxt.setText("");
        passwordInpTxt.setText("");
        genderSelection.clearSelection();
        locationCBox.setSelectedIndex(0);
        policyCheckBtn.setSelected(false);
    }//GEN-LAST:event_clearBtnActionPerformed

    private void policyCheckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policyCheckBtnActionPerformed
        if (policyCheckBtn.isSelected()) {
            signUpBtn.setEnabled(true);
        } else {
            signUpBtn.setEnabled(false);
        }
    }//GEN-LAST:event_policyCheckBtnActionPerformed

    private void locationCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationCBoxActionPerformed
        var selectedLocation = (Location) locationCBox.getSelectedItem();
        zipCodeLbl.setText("ZipCode: " + selectedLocation.getCode());
    }//GEN-LAST:event_locationCBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JComboBoxDemo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JComboBoxDemo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JComboBoxDemo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JComboBoxDemo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JComboBoxDemo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel genderLbl;
    private javax.swing.JRadioButton genderRadBtnFemale;
    private javax.swing.JRadioButton genderRadBtnFlex;
    private javax.swing.JRadioButton genderRadBtnMale;
    private javax.swing.ButtonGroup genderSelection;
    private javax.swing.JComboBox<Location> locationCBox;
    private javax.swing.JLabel locationLbl;
    private javax.swing.JPasswordField passwordInpTxt;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JCheckBox policyCheckBtn;
    private javax.swing.JLabel resultLbl;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JTextField usernameInpTxt;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JLabel zipCodeLbl;
    // End of variables declaration//GEN-END:variables
}
