/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package L10_GUI.S13_JOptionPane;

import javax.swing.JOptionPane;

/**
 *
 * @author NGHIA NGUYEN
 */
public class JOptionPaneDemo extends javax.swing.JFrame {

    /**
     * Creates new form JOptionPaneDemo
     */
    public JOptionPaneDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showMsgBtn0 = new javax.swing.JButton();
        showMsgBtn1 = new javax.swing.JButton();
        showMsgBtn2 = new javax.swing.JButton();
        showMsgBtn3 = new javax.swing.JButton();
        showMsgBtn4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        showMsgBtn0.setText("Show messages");
        showMsgBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMsgBtn0ActionPerformed(evt);
            }
        });

        showMsgBtn1.setText("Show messages with title");
        showMsgBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMsgBtn1ActionPerformed(evt);
            }
        });

        showMsgBtn2.setText("Show messages with title and icon");
        showMsgBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMsgBtn2ActionPerformed(evt);
            }
        });

        showMsgBtn3.setText("Show input dialog");
        showMsgBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMsgBtn3ActionPerformed(evt);
            }
        });

        showMsgBtn4.setText("Show dialog with confirmation");
        showMsgBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMsgBtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showMsgBtn4)
                    .addComponent(showMsgBtn3)
                    .addComponent(showMsgBtn2)
                    .addComponent(showMsgBtn1)
                    .addComponent(showMsgBtn0))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(showMsgBtn0)
                .addGap(18, 18, 18)
                .addComponent(showMsgBtn1)
                .addGap(18, 18, 18)
                .addComponent(showMsgBtn2)
                .addGap(18, 18, 18)
                .addComponent(showMsgBtn3)
                .addGap(18, 18, 18)
                .addComponent(showMsgBtn4)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showMsgBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMsgBtn0ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Message body");
    }//GEN-LAST:event_showMsgBtn0ActionPerformed

    private void showMsgBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMsgBtn1ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Message body", "Message title", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_showMsgBtn1ActionPerformed

    private void showMsgBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMsgBtn2ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Message body", "Message title", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_showMsgBtn2ActionPerformed

    private void showMsgBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMsgBtn3ActionPerformed
        String inputText = JOptionPane.showInputDialog(rootPane,"Please enter your name:");
        
        if (inputText == null){
            inputText = "John Wick";
        }
        
        JOptionPane.showMessageDialog(rootPane, "Your name is: " + inputText);
    }//GEN-LAST:event_showMsgBtn3ActionPerformed

    private void showMsgBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMsgBtn4ActionPerformed
        
        // Brings up a dialog with the options Yes, No and Cancel; with the title, Select an Option.
        int answer = JOptionPane.showConfirmDialog(rootPane, "Are you hungry?");
        
        String answerText = "";
        
        if(answer == JOptionPane.YES_OPTION){ // YES_OPTION = 0;
            answerText = "YES";
        } else if(answer == JOptionPane.NO_OPTION){ // NO_OPTION = 1;
            answerText = "NO";
        } else if(answer == JOptionPane.CANCEL_OPTION){ // CANCEL_OPTION = 2;
            answerText = "CANCEL";
        }
        
        
        JOptionPane.showMessageDialog(rootPane, "You said " + answerText);
    }//GEN-LAST:event_showMsgBtn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JOptionPaneDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JOptionPaneDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JOptionPaneDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JOptionPaneDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JOptionPaneDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton showMsgBtn0;
    private javax.swing.JButton showMsgBtn1;
    private javax.swing.JButton showMsgBtn2;
    private javax.swing.JButton showMsgBtn3;
    private javax.swing.JButton showMsgBtn4;
    // End of variables declaration//GEN-END:variables
}
